create schema if not exists data;

CREATE SEQUENCE IF NOT EXISTS data.migracion_ugs_seq 
     START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS data.ugs_seq 
     START WITH 100000 INCREMENT BY 1;

create table if not exists data.ugs(
    id BIGINT PRIMARY KEY,
    NOMBRE_CORTO VARCHAR2(20) NOT NULL,
    NOMBRE_LARGO VARCHAR2(150) NOT NULL,
    ACCESOS VARCHAR2(255),
    DESCRIPCION VARCHAR2(255),
    BARRIO_ID BIGINT,
    LOCALIDAD_ID BIGINT NOT NULL,
    CIUDAD_ID BIGINT,
    PROVINCIA_ID INT,
    FECHA_CREACION TIMESTAMP NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP,
    DESTACADO BOOLEAN
);

CREATE SEQUENCE IF NOT EXISTS data.migracion_georreferencias_seq
     START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS data.georreferencias_seq
     START WITH 100000 INCREMENT BY 1;

create table if not exists data.georreferencias(
    id BIGINT PRIMARY KEY,
    ESTADO_EDILICIO VARCHAR2(255),
    EDIFICIO_ELECTORAL BOOLEAN,
    CALLE VARCHAR2(100),
    ENTRE1 VARCHAR2(100),
    ENTRE2 VARCHAR2(100),
    NUMERO VARCHAR2(20),
    DEPTO VARCHAR2(20),
    OBSERVACIONES VARCHAR2(255),
    UG_ID BIGINT,
    LOCALIDAD_ID BIGINT,
    BARRIO_ID BIGINT,
    CIUDAD_ID BIGINT,
    PROVINCIA_ID INT,
    FECHA_CREACION TIMESTAMP NOT NULL, 
    FECHA_ACTUALIZACION TIMESTAMP
);